plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.3'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'daeun'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}
configurations.all {
	resolutionStrategy.eachDependency { details ->
		if (details.requested.group == 'io.jsonwebtoken') {
			details.useVersion '0.12.5'
		}
	}
}


repositories {
	mavenCentral()
}

dependencies {
	//DB랑 통신할 때 쓰이는 거 (ORM) -> Object Relational Mapping (Hibernate)
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	//보안 (인증, 검증)
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	//유효성 검증
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	//웹 애플리케이션 개발
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
	//귀찮은 코드 제거
	compileOnly 'org.projectlombok:lombok'
	//mysql 연동
	runtimeOnly 'com.mysql:mysql-connector-j'

	annotationProcessor 'org.projectlombok:lombok'

	testAnnotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.projectlombok:lombok'
	implementation( 'io.jsonwebtoken:jjwt:0.9.1')
	implementation ('javax.xml.bind:jaxb-api:2.3.1')
/*
	implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'


	constraints {
		add("implementation", "io.jsonwebtoken:jjwt-api:0.12.5")
		add("runtimeOnly", "io.jsonwebtoken:jjwt-impl:0.12.5")
		add("runtimeOnly", "io.jsonwebtoken:jjwt-jackson:0.12.5")
	}
*/

	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	testImplementation 'org.springframework.security:spring-security-test'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}


/*
tasks.named('test') {
	useJUnitPlatform()
	//include 'Test.class' //이 라인 추가

}
*/
